version: "3"
services:
  backend:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    command: /bin/bash -c 'sleep infinity'
    depends_on:
      - postgres-vtb
    environment:
      - INSIDE_DOCKER=true
    working_dir: /workspace
    volumes:
      - .:/workspace
      # cache VS Code Server extensions
      - vs-server-extensions:/root/.vscode-server/extensions
      - vs-server-insider-extensions:/root/.vscode-server-insiders/extensions

  postgres-vtb:
    image: library/postgres:13
    container_name: postgres-vtb
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  es-vtb:
    container_name: es-vtb
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  db-data:
  vs-server-extensions:
  vs-server-insider-extensions:
