"""create_payments_table
Revision ID: 77bf8f4f3aac
Revises:
Create Date: 2021-12-02 19:55:49.541684
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77bf8f4f3aac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = op.get_context().version_table_schema
    op.create_table(
        "payment",
        sa.Column("identifier", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.Enum("PAID", "CANCELED", name="paymentstatus"), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = op.get_context().version_table_schema
    op.drop_table("payment", schema=schema)
    # ### end Alembic commands ###
