"""create_rental_table
Revision ID: 045e5ad66dda
Revises:
Create Date: 2021-11-30 19:41:13.286016
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "045e5ad66dda"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = op.get_context().version_table_schema
    op.create_table(
        "rental",
        sa.Column("identifier", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("car_uid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.Enum("NEW", "IN_PROGRESS", "FINISHED", "CANCELED", name="rentalstatus"), nullable=True),
        sa.Column("payment_uid", postgresql.UUID(as_uuid=True), nullable=True),
        sa.PrimaryKeyConstraint("identifier"),
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = op.get_context().version_table_schema
    op.drop_table("rental", schema=schema)
    # ### end Alembic commands ###
